### ISSUE TITLE
Component - Button

### ISSUE THREAD

**Issue by KevinTss** [HackYourFutureBelgium/hackyourfuture.be#264]
# Button

## Specifications

- Should render a `<button>` HTML element
- There are 2 sizes: `small` and `medium`
- There are 3 variants: `default`, `primary`, `secondary`
  - Default: Has transparent background and only a visible background on hover
  - Primary: Has the primary color
  - Secondary: Has an opacity on the background and no primary color
- Color 

### Helpers

```css
button {
  /* Small size */
  padding: 10px 24px;
  gap: 10px;

  /* Medium size */
  padding: 10px 32px;
  gap: 16px;

  /* Default variant */
  background: #295BF6;
  /* On hover for default */
  background: rgba(255, 255, 255, 0.1);

  /* Secondary variant */
  background: rgba(255, 255, 255, 0.1);

  /* Common */
  border-radius: 8px;
  color: #FFFFFF;
}
```

### We should use it as this:

```jsx
import { Button } form '...'

const Component = () => (
  <div>
    <Button onClick={...}>
      Discover more
      <RightArrowIcon />
    </Button>
  </div>
)
```
# Images

![Image](https://user-images.githubusercontent.com/39580007/221418839-51735942-35f6-4763-8908-d3093e05726b.png)
![Image](https://user-images.githubusercontent.com/39580007/221418841-27607380-d9ab-4223-a30c-860934b1a580.png)
![Image](https://user-images.githubusercontent.com/39580007/221418840-af61346a-b8e2-47a2-959e-02a1d05bee09.png)
![Image](https://user-images.githubusercontent.com/39580007/221419307-ff03bbed-c052-4628-9dd6-318abb25f690.png)
